# -*- coding: utf-8 -*-
"""Clase 7 parte 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fq3FQuHef9vdQHikwKgzhxV5dnPSPuh5

**10.3 Tarea: Con la clase Persona**
"""

class Persona:
    def __init__(self, nombre, edad):
        self._nombre = nombre
        self._edad = edad

    @property
    def nombre(self):
        print("Se está usando el método getter")
        return self._nombre

    @nombre.setter
    def nombre(self, nombre):
        print("Se está usando el método setter")
        self._nombre = nombre

    @property
    def edad(self):
        print("Se está usando el método getter")
        return self._edad

    @edad.setter
    def edad(self, edad):
        print("Se está usando el método setter")
        self._edad = edad

    def mostrar_detalles(self):
        print(f"Nombre: {self._nombre}")
        print(f"Edad: {self._edad}")


# Crear tres objetos
persona1 = Persona("Juan", 20)
persona2 = Persona("María", 25)
persona3 = Persona("Pedro", 30)

# Mostrar datos originales
persona1.mostrar_detalles()
persona2.mostrar_detalles()
persona3.mostrar_detalles()

# Modificar usando setters
persona1.nombre = "Carlos"
persona1.edad = 22

persona2.nombre = "Lucía"
persona2.edad = 27

persona3.nombre = "Martín"
persona3.edad = 32

# Mostrar los cambios usando getters
print("\nDatos modificados:")

print(persona1.nombre)
print(persona1.edad)

print(persona2.nombre)
print(persona2.edad)

print(persona3.nombre)
print(persona3.edad)