# -*- coding: utf-8 -*-
"""Ejercicio de Colecciones 1 del 4.1 al 4.5".ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1ub_SFY2WWRbh3RQpxBDDOzU4V6qWVS

**4.1  Ejercicio de Colecciones 1 -> (Ejercicio 1) Eliminar duplicados de una lista**
"""

# Ejercicio 1: Eliminar duplicados de una lista
# Escriba un programa donde tenga una lista y que a continuación
# elimine los elementos repetidos, por último mostrar la lista.

# Creamos una lista
nombres = ["Juan", "Pedro", "Lucas", "Juan", "Pedro", "Lucas", "Ana"]
#Eliminamos los elementos repetidos
nombres = list(set(nombres))
# Mostramos la lista
print(nombres)

"""4.2 Ejercicio de Colecciones 2 -> (Ejercicio 2) Operaciones de conjuntos con listas"""

# Ejercicio 2: Operaciones de conjuntos con listas
# Escriba un programa que tenga 2 listas y que a continuación
# cree las siguientes listas (en las que no deben haber repetición)
# 1 Lista de palabras que aparecen en las listas
# 2 Lista de palabras que aparecen en la primera lista, pero no en la segunda
# 3 lista de palabras que aparecen en la segunda lista, pero no en la primera
# 4 lista de palabras que aparecen en ambas listas
# Ejercicio 2: Operaciones de conjuntos con listas

lista1 = ["Juan", "Pedro", "Lucas", "Ana", "Juan"]
lista2 = ["Pedro", "Carlos", "Ana", "Sofia", "Pedro"]

# 1. Palabras que aparecen en las listas
lista1_y_lista2 = list(set(lista1) | set(lista2))

# 2. Palabras que aparecen en la primera lista, pero no en la segunda
solo_lista1 = list(set(lista1) - set(lista2))

# 3. Palabras que aparecen en la segunda lista, pero no en la primera
solo_lista2 = list(set(lista2) - set(lista1))

# 4. Palabras que aparecen en ambas listas
ambas_listas = list(set(lista1) & set(lista2))

print("Nombres de ambas listas:", lista1_y_lista2)
print("Solo de la primera lista:", solo_lista1)
print("Solo de la segunda lista:", solo_lista2)
print("Nombres que aparecen en ambas:", ambas_listas)

"""4.3 Ejercicio de Colecciones 3 -> (Ejercicio 3) Agregar personajes a una lista"""

# Ejercicio 3: Agregar personajes a una lista
# Escriba un programa donde cree una lista con los siguientes personajes del señor de los anillos
# Nombre: Aragon
# Clase: Guerrero
# Raza: Dunadan del norte

# Nombre: Gandalf
# Clase: Mago
# Raza: Istar

# Nombre: Legolas
# Clase: Arquero
# Raza: Elfo Sindar
# Ejercicio 3: Agregar personajes a una lista - Clase 4

# Creamos la lista con diccionarios
personajes = [
    {"Nombre": "Aragon", "Clase": "Guerrero", "Raza": "Dunadan del norte"},
    {"Nombre": "Gandalf", "Clase": "Mago", "Raza": "Istar"},
    {"Nombre": "Legolas", "Clase": "Arquero", "Raza": "Elfo Sindar"}
]

# Mostramos la lista
for personaje in personajes:
    print(personaje)

"""4.4 Ejercicio 1 con Matemáticas y la clase math"""

import math  # importamos la clase math para hacer uso de la funcion sqrt(raiz cuadrada)

# Dada la siguiente tupla
tupla = (13, 1, 8, 3, 2, 5, 8)  # Definimos la tupla

# Crear una lista que solo incluya los números menores a 5
# e imprima por consola [1, 3, 2]
lista = []  # Definimos la lista

# Filtramos los elementos menores a 5 de la tupla
for elemento in tupla:
    if elemento < 5:
        lista.append(elemento)

print(lista)

# Ejercicio de matematicas
# Para sacar la raiz cuadrada de un número positivo
numero = int(input('Digite un numero positivo: '))

while numero < 0:
    print('Error -> Deberia ser un número positivo')
    numero = int(input('Digite un número positivo: '))

print(f'\nSu raíz cuadrada es: {math.sqrt(numero):.2f}')

"""4.5 Recorremos el Diccionario seleccionArgentina"""

# Los diccionarios pueden almacenar diferente tipos de datos
diccionario2 = {'Ariel': {'Edad': 40, 'Altura': 1.83}, 'Osvaldo': [45, 1.85], 'Natalia': [35, 1.67]}
print(diccionario2)

# Diccionario para datos de la selección Argentina
seleccionArgentina = {
    10: {'Nombre': 'Lionel Messi', 'Edad': 35, 'Altura': 1.70, 'Precio': '50 Millones', 'Posicion': 'Extremo Derecho'},
    11: {'Nombre': 'Ángel Di Maria', 'Edad': 34, 'Altura': 1.80, 'Precio': '12 Millones', 'Posicion': 'Extremo Derecho'},
    21: {'Nombre': 'Paulo Dybala', 'Edad': 28, 'Altura': 1.77, 'Precio': '35 Millones', 'Posicion': 'Media Punta'},
    19: {'Nombre': 'Nicolás Otamendi', 'Edad': 34, 'Altura': 1.83, 'Precio': '3.5 Millones', 'Posicion': 'Defensa Central'},
    1: {'Nombre': 'Franco Armani', 'Edad': 35, 'Altura': 1.89, 'Precio': '3.5 Millones', 'Posicion': 'Portero'}
}

# Recorremos el diccionario
for i in seleccionArgentina:
    print(f'{i} -> {seleccionArgentina[i]}')