# -*- coding: utf-8 -*-
"""Clase 5.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Wzc_DweA1VQlAdTSSoezAoCmGBdd0M6

**6.2 Ejercicio 11 Agenda Telefónica**
"""

# Ejercicio 11: Agenda telefonica
# Hacer un programa que simule una agenda de contactos. Crear un
# diccionario donde la clave sea el nombre del usuario y el valor
# sea el telefono, el programa tendra el siguiente menú de opciones:
# 1. Nuevo contacto
# 2. Borrar contacto
# 3. Ver contactos existentes
# 4. Salir}

agenda = {}

while True:
    print("\n--- AGENDA TELEFÓNICA ---")
    print("1. Nuevo contacto")
    print("2. Borrar contacto")
    print("3. Ver contactos existentes")
    print("4. Salir")

    opcion = input("Ingrese una opción: ")

    if opcion == "1":
        nombre = input("Ingrese el nombre: ")
        telefono = input("Ingrese el teléfono: ")
        agenda[nombre] = telefono
        print("Contacto agregado correctamente.")

    elif opcion == "2":
        nombre = input("Ingrese el nombre del contacto a borrar: ")

        if nombre in agenda:
            del agenda[nombre]
            print("Contacto borrado correctamente.")
        else:
            print("El contacto no existe.")

    elif opcion == "3":
        if len(agenda) == 0:
            print("No hay contactos.")
        else:
            print("\nContactos existentes:")
            for nombre, telefono in agenda.items():
                print(nombre, ":", telefono)

    elif opcion == "4":
        print("Saliendo de la agenda...")
        break

    else:
        print("Opción inválida.")