# -*- coding: utf-8 -*-
"""Clase 5.9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Wzc_DweA1VQlAdTSSoezAoCmGBdd0M6

**6.9.1 Ejercicio Funciones 01**
"""

# Ejercicio 01: Crear una función para sumar los valores recibidos de tipo
# numéricos, utilizando argumentos variables *args como parametro de la
# Función y agregar como resultado la suma de todos los valores pasados
# como argumentos.

def sumar(*args):
    resultado = 0

    for numero in args:
        resultado += numero

    return resultado


print(sumar(5, 10, 15))