# -*- coding: utf-8 -*-
"""Clase2.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKo1NsJVPkhPSFmORqrDlHELjUY2DRIS

**2.4 Repaso y más conceptos de Tuplas**
"""

# Repaso de Tuplas
tupla = (4, 'Hola', 6.78, [1, 2, 78], 4, 'Hola') # Puede tener diferentes tipos de datos dentro
print(tupla)

print(4 in tupla) # Acción booleana, su respuesta es de tipo booleana
# Lo que podemos usar dentro de tuplas son: index, count, len
# En tuplas se puede convertir de tupla a lista y de lista a tupla