# -*- coding: utf-8 -*-
"""Clase 2.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_OdILOZdiujSxbjZmDfvnDq2yU2RwUv

**2.1 Tipo set o conjunto**
"""

# Tipo set
planetas = {'Marte', 'Júpiter', 'Venus'}
print(len(planetas)) # Usamos la función len = length significa largo

# Revisar si un elemento existe dentro de set
print('Júpiter' in planetas)

# Agregar un elemento
planetas.add('Tierra') # add es una función
planetas.add('Tierra')
planetas.add('Tierra')
planetas.add('Tierra') # estas lineas de codigo repetidas estan de ejemplo para que se vea que no se repite tierra.
print(planetas)

"""2.2"""

# Eliminar elementos, puede arrojar un error si el elemento no existe
planetas.remove('Júpiter') # Esta función ante un mal ingreso u inexistencia del elemento da error
print(planetas)
planetas.discard('tierra') # Esta función no nos presenta ningun error
print(planetas)

# Limpiar set o conjunto
planetas.clear()
print(planetas)

# Eliminar set o conjunto
del planetas
print(planetas) # al eliminar nos muestra un error